In [1]:
import pulp as pl
solver_list = pl.listSolvers()
print(solver_list)

Cardinal Optimizer v7.1.3. Build date Apr 29 2024
Copyright Cardinal Operations 2024. All Rights Reserved

['GLPK_CMD', 'PYGLPK', 'CPLEX_CMD', 'CPLEX_PY', 'GUROBI', 'GUROBI_CMD', 'MOSEK', 'XPRESS', 'XPRESS', 'XPRESS_PY', 'PULP_CBC_CMD', 'COIN_CMD', 'COINMP_DLL', 'CHOCO_CMD', 'MIPCL_CMD', 'SCIP_CMD', 'FSCIP_CMD', 'SCIP_PY', 'HiGHS', 'HiGHS_CMD', 'COPT', 'COPT_DLL', 'COPT_CMD']


In [2]:
solver_list = pl.listSolvers(onlyAvailable=True)
print(solver_list)

Cardinal Optimizer v7.1.3. Build date Apr 29 2024
Copyright Cardinal Operations 2024. All Rights Reserved

['GLPK_CMD', 'GUROBI', 'GUROBI_CMD', 'PULP_CBC_CMD', 'COIN_CMD', 'HiGHS', 'COPT', 'COPT_DLL', 'COPT_CMD']


In [ ]:
pyomo help --solvers

In [ ]:
import linopy
import pandas as pd
import xarray as xr
m = linopy.Model()
time = pd.Index(range(10), name='time')

x = m.add_variables(lower=0, coords=[time], name='x', )
y = m.add_variables(lower=0, coords=[time], name='y')

factor = pd.Series(time, index=time)

con1 = m.add_constraints(3*x + 7*y >= 10*factor, name='con1')
con2 = m.add_constraints(5*x + 2*y >= 3*factor, name='con2')

m.add_objective(x + 2*y)
m.solve()

m.solve();
sol = m.solution.to_dataframe()
sol.plot(grid=True, ylabel='Optimal Value')

In [ ]:
import linopy

m = linopy.Model()
import pandas as pd
time = pd.Index(range(10), name='time')

x = m.add_variables(lower=0, coords=[time], name='x', )
y = m.add_variables(lower=0, coords=[time], name='y')


In [ ]:
import linopy
import numpy as np

# 定义变量

m = linopy.Model()

x = m.add_variables(name='x',lower=0)
y = m.add_variables(name='y',lower=0)

# 定义目标函数
objective = 3 * x + 2 * y

# 定义约束
A = np.array([[1, 2], [-1, 1]])
b = np.array([2, 1])

# 添加约束到问题中

# 创建问题实例
m.add_constraints(A @ [x, y] <= b)

m.add_objective(objective)

# 求解问题
solution = m.solve()

# 打印结果
print("Solution:", solution.value)
print("Optimal values of variables:", solution.variables)


In [ ]:
from optlang.scipy_interface import Model, Variable, Constraint, Objective

# All the (symbolic) variables are declared, with a name and optionally a lower and/or upper bound.
x1 = Variable('x1', lb=0, ub = 100)
x2 = Variable('x2', lb=0)
x3 = Variable('x3', lb=0)

# A constraint is constructed from an expression of variables and a lower and/or upper bound (lb and ub).
c1 = Constraint(x1 + x2 + x3, lb = -100 ,ub=100)
c2 = Constraint(10 * x1 + 4 * x2 + 5 * x3, ub=200)
c3 = Constraint(2 * x1 + 2 * x2 + 6 * x3, ub=300)

# An objective can be formulated
obj = Objective(10 * x1 + 6 * x2 + 4 * x3, direction='max')

# Variables, constraints and objective are combined in a Model object, which can subsequently be optimized.
model = Model(name='Simple model')
model.objective = obj
# model.configuration.lp_method = 'simplex'
model.add([c1, c2, c3])

status = model.optimize()

print("status:", model.status)
print("objective value:", model.objective.value)
print("----------")
for var_name, var in model.variables.iteritems():
    print(var_name, "=", var.primal)

In [ ]:
import linopy
import numpy as np

# 定义线性规划问题的系数
A = np.array([[1, 2], [-1, 1], [2, 1]])  # 不等式约束的系数矩阵
b = np.array([1, 0, 3])  # 不等式约束的右侧常数
c = np.array([-1, -2])  # 目标函数的系数

# 创建 linopy 模型
model = linopy.Model()

# 添加变量
x = model.add_variables(2)

# 添加约束
for i in range(len(A)):
    model.add_constraints(A[i, :] * x <= b[i])

# 设置目标函数
model.set_objective(c @ x)

# 求解模型
solution = model.optimize()

# 打印结果
print("最优解 x:", solution.x)
print("最优值:", solution.objective_value)


In [1]:
import pulp as pl
solver_list = pl.listSolvers()
print(solver_list)

Cardinal Optimizer v7.1.3. Build date Apr 29 2024
Copyright Cardinal Operations 2024. All Rights Reserved
2024-05-24 00:09:32 [INFO] checks license for COPT v7.1.3 20240429
2024-05-24 00:09:32 [WARN] no license files in current working folder: /home/keshi/Code/Python/dingo/tests
2024-05-24 00:09:32 [WARN] no license files in binary folder: /usr/local/bin
2024-05-24 00:09:32 [WARN] no license files in HOME folder: /home/keshi/copt
2024-05-24 00:09:32 [INFO] empty environment variable: COPT_LICENSE_DIR
2024-05-24 00:09:32 [WARN] no license files in EV 'COPT_LICENSE_DIR': 

No license found. Starting COPT with size limitations for non-commercial use
Please apply for a license from www.shanshu.ai/copt


['GLPK_CMD', 'PYGLPK', 'CPLEX_CMD', 'CPLEX_PY', 'GUROBI', 'GUROBI_CMD', 'MOSEK', 'XPRESS', 'XPRESS', 'XPRESS_PY', 'PULP_CBC_CMD', 'COIN_CMD', 'COINMP_DLL', 'CHOCO_CMD', 'MIPCL_CMD', 'SCIP_CMD', 'FSCIP_CMD', 'SCIP_PY', 'HiGHS', 'HiGHS_CMD', 'COPT', 'COPT_DLL', 'COPT_CMD']


In [8]:
import pulp as pl
solver_list = pl.listSolvers(onlyAvailable=True)
print(solver_list)

Cardinal Optimizer v7.1.3. Build date Apr 29 2024
Copyright Cardinal Operations 2024. All Rights Reserved
2024-05-24 00:15:12 [INFO] checks license for COPT v7.1.3 20240429
2024-05-24 00:15:12 [WARN] no license files in current working folder: /home/keshi/Code/Python/dingo/tests
2024-05-24 00:15:12 [WARN] no license files in binary folder: /usr/local/bin
2024-05-24 00:15:12 [WARN] no license files in HOME folder: /home/keshi/copt
2024-05-24 00:15:12 [INFO] empty environment variable: COPT_LICENSE_DIR
2024-05-24 00:15:12 [WARN] no license files in EV 'COPT_LICENSE_DIR': 

No license found. Starting COPT with size limitations for non-commercial use
Please apply for a license from www.shanshu.ai/copt


['GLPK_CMD', 'GUROBI', 'GUROBI_CMD', 'PULP_CBC_CMD', 'COIN_CMD', 'HiGHS', 'COPT']


In [9]:
import pulp as pl
!source ~/.zshrc
solver_list = pl.listSolvers(onlyAvailable=True)
solver_all = pl.listSolvers()
print(solver_list)
print(solver_all)

Cardinal Optimizer v7.1.3. Build date Apr 29 2024
Copyright Cardinal Operations 2024. All Rights Reserved
2024-05-24 00:15:31 [INFO] checks license for COPT v7.1.3 20240429
2024-05-24 00:15:31 [WARN] no license files in current working folder: /home/keshi/Code/Python/dingo/tests
2024-05-24 00:15:31 [WARN] no license files in binary folder: /usr/local/bin
2024-05-24 00:15:31 [WARN] no license files in HOME folder: /home/keshi/copt
2024-05-24 00:15:31 [INFO] empty environment variable: COPT_LICENSE_DIR
2024-05-24 00:15:31 [WARN] no license files in EV 'COPT_LICENSE_DIR': 

No license found. Starting COPT with size limitations for non-commercial use
Please apply for a license from www.shanshu.ai/copt


Cardinal Optimizer v7.1.3. Build date Apr 29 2024
Copyright Cardinal Operations 2024. All Rights Reserved
2024-05-24 00:15:32 [INFO] checks license for COPT v7.1.3 20240429
2024-05-24 00:15:32 [WARN] no license files in current working folder: /home/keshi/Code/Python/dingo/tests
2024-05-24 

In [ ]:
import highspy

In [ ]:
import pulp as pl
solver_list = pl.listSolvers()
print(solver_list)

In [ ]:
import pulp
pulp.__version__

In [ ]:
import glpk
import numpy as np

# 定义模型
model = glpk.LPX()

# 定义反应
reactions = ['R1', 'R2', 'R3']
v_min = {'R1': 0, 'R2': 0, 'R3': 0}  # 下限速率
v_max = {'R1': 10, 'R2': 10, 'R3': 10}  # 上限速率

# 添加反应变量到模型
v = {r: model.cols.add(name=r, obj=1.0, bounds=(v_min[r], v_max[r])) for r in reactions}

# 定义代谢物
metabolites = ['M1', 'M2', 'M3', 'M4', 'M5', 'M6']
S = {m: model.cols.add(name=m, obj=0.0, bounds=(0, None)) for m in metabolites}

# 定义平衡方程系数
S_ij = {
    ('R1', 'M1'): -1, ('R1', 'M2'): 1,
    ('R2', 'M2'): -1, ('R2', 'M3'): 1,
    ('R3', 'M3'): -1, ('R3', 'M4'): 1, ('R3', 'M5'): 1, ('R3', 'M6'): -1
}

# 添加平衡方程到模型
for r in reactions:
    for m in metabolites:
        if (r, m) in S_ij:
            model.rows.add(name=f"{r}_{m}", senses='E', rhs=0.0)
            model.rows[-1].matrix = [(v[r], S_ij[(r, m)]), (S[m], -1.0)]

# 设置目标函数（最小化总反应速率）
model.obj.maximize = False

# 求解模型
model.simplex()

# 输出结果
print("Optimal Solution:")
for r in reactions:
    print(f"Reaction {r}: {v[r].value}")
for m in metabolites:
    print(f"Metabolite {m}: {S[m].value}")


In [ ]:
import glpk
glpk.LPX()

In [ ]:
import glpk
glpk.__version__

In [ ]:
import glpkpy

In [ ]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import numpy as np

# 假设 X 是你的数据矩阵，每一行是一个样本，每一列是一个特征
X = np.array([[1, 5 ,3 ,1], 
              [4,-4, 6,6], 
              [1, 4, 3, 2],
              [4, 4, 2, 2],
              [5, 5, 2, 4]])

# 数据标准化
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 创建 PCA 对象
pca = PCA(n_components=2)  # 假设我们想要降维到2维

# 应用 PCA
X_pca = pca.fit_transform(X_scaled)

# 输出降维后的数据
print('Reduced Data:')
print(X_pca)


In [ ]:
##Python实现PCA
import numpy as np
def pca(X,k):#k is the components you want
  #mean of each feature
  n_samples, n_features = X.shape
  mean=np.array([np.mean(X[:,i]) for i in range(n_features)])
  #normalization
  norm_X=X-mean
  #scatter matrix
  scatter_matrix=np.dot(np.transpose(norm_X),norm_X)
  #Calculate the eigenvectors and eigenvalues
  eig_val, eig_vec = np.linalg.eig(scatter_matrix)
  eig_pairs = [(np.abs(eig_val[i]), eig_vec[:,i]) for i in range(n_features)]
  # sort eig_vec based on eig_val from highest to lowest
  eig_pairs.sort(reverse=True)
  # select the top k eig_vec
  feature=np.array([ele[1] for ele in eig_pairs[:k]])
  #get new data
  data=np.dot(norm_X,np.transpose(feature))
  return data

X = np.array([[1, 5 ,3 ,1], 
              [4,-4, 6,6], 
              [1, 4, 3, 2],
              [4, 4, 2, 2],
              [5, 5, 2, 4]])
print(pca(X,2))

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm

# 正样本和负样本
positive_samples = np.array([[1, 1], [2, 1], [2, 3]])
negative_samples = np.array([[-1, -1], [0, -3], [-2, -4]])

# 标签：1 代表正样本，-1 代表负样本
positive_labels = np.ones(len(positive_samples))
negative_labels = -np.ones(len(negative_samples))

# 合并样本和标签
samples = np.concatenate((positive_samples, negative_samples), axis=0)
labels = np.concatenate((positive_labels, negative_labels), axis=0)

# 创建SVM分类器
clf = svm.SVC(kernel='linear', C=1.0)

# 训练模型
clf.fit(samples, labels)

# 打印支持向量
print("Support vectors:", clf.support_vectors_)

# 打印超平面的法向量
print("Normal vector to the decision hyperplane:", clf.coef_)

# 打印超平面的截距
print("Intercept to the decision hyperplane:", clf.intercept_)

# 绘制数据点
plt.scatter(positive_samples[:, 0], positive_samples[:, 1], color='blue', label='Positive')
plt.scatter(negative_samples[:, 0], negative_samples[:, 1], color='red', label='Negative')

# 绘制支持向量
plt.scatter(clf.support_vectors_[:, 0], clf.support_vectors_[:, 1], color='green', label='Support Vectors')

# 绘制决策边界
ax = plt.gca()
xlim = ax.get_xlim()
ylim = ax.get_ylim()

# 创建网格来评估模型
xx = np.linspace(xlim[0], xlim[1], 30)
yy = np.linspace(ylim[0], ylim[1], 30)
YY, XX = np.meshgrid(yy, xx)
xy = np.vstack([XX.ravel(), YY.ravel()]).T
Z = clf.decision_function(xy).reshape(XX.shape)

# 绘制决策边界和边界
ax.contour(XX, YY, Z, colors='k', levels=[-1, 0, 1], alpha=0.5, linestyles=['--', '-', '--'])

# 绘制支持向量到决策边界的距离
ax.scatter(clf.support_vectors_[:, 0], clf.support_vectors_[:, 1], s=100, linewidth=1, facecolors='none', edgecolors='k')

# 设置图例
plt.legend()

# 显示图形
plt.show()


In [5]:
import numpy as np

# 定义sigmoid函数
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# 定义输入、权重、偏置和学习率
x = np.array([0.80, 0.55, 0.20, 0.10])
W1 = np.array([[0.10, 0.40, 0.35], [0.15, 0.20, 0.25], [0.05, 0.35, 0.40], [0.20, 0.25, 0.15]])
W1 = W1.transpose()
b1 = np.array([0.15, 0.10, 0.25])
W2 = np.array([[0.20, 0.40], [0.35, 0.15], [0.30, 0.50]])
W2 = W2.transpose()
b2 = np.array([0.30, 0.20])
y = np.array([1, 0])
η = 0.01

# 前向传播
a1 = np.dot(W1, x) + b1
z1 = sigmoid(a1)
a2 = np.dot(W2, z1) + b2
z2 = sigmoid(a2)

# # 计算损失
# L = -(y * np.log(z2) + (1 - y) * np.log(1 - z2))

# # 后向传播
# δ2 = z2 - y
# δ1 = np.dot(W2.T, δ2) * z1 * (1 - z1)

# # 更新权重
# W2 -= η * np.dot(δ2, z1.T)
# W1 -= η * np.dot(δ1, x.T)

# # 输出更新后的W1[4,1]和W2[1,1]
# print("Updated W1[4,1]:", W1[3, 0])
# print("Updated W2[1,1]:", W2[0, 1])


In [6]:
a1 

array([0.3425, 0.625 , 0.7625])

In [7]:
z1

array([0.58479767, 0.65135486, 0.68189626])

In [8]:
a2

array([0.84950262, 0.87257043])

In [10]:
z2

array([0.70046279, 0.70528027])

In [15]:
*(1-0.7005)*0.7005*0.1

0.020979975

In [19]:
0.58479767*(1-0.58479767)*0.1

0.02428093551625711

In [20]:
0.02428093551625711*-0.342

-0.008304079946559932